# config/default.yaml
postgres:
  database: aiohttp_security 
  user: aiohttp_security
  password: aiohttp_security
  host: localhost
  port: 5432
  minsize: 1
  maxsize: 5
redis:
  host: localhost
  port: 6379
app:
  host: 127.0.0.1
  port: 9001
